"""Bioregistry -> ``lake.ref.bioregistry``: canonical identifier prefixes.

The registry export (CC0, auto-generated by GitHub Actions on every merge) is
what backs the manual bioregistry.io lookups this lake's own column-naming
convention already depends on (2026-08-10 session: ``ncbitaxon_id`` not
``ncbi_taxon_id``, verified by hand against bioregistry.io). Landing it as a
table makes that lookup a join instead of a web fetch, for every source in
this lake, not just the one that happened to prompt it.

Only the columns this lake actually has a use for are kept -- the full export
carries ~30 more columns of per-external-registry local IDs (miriad, n2t,
obofoundry, ols, wikidata, ...) that serve cross-registry resolution, not our
own naming/validation use case. Add them if that need shows up; don't land
30 unused columns speculatively.
"""

from __future__ import annotations

from pathlib import Path

import duckdb

from ... import ops
from ...config import Settings, get_settings
from ...connect import LAKE, csv_source, lake_connect, raw_dir, upsert
from ...download import download

_RAW = "bioregistry"

# Bioregistry's own TSV header -> our column name. `identifier` -> `prefix`:
# the source calls it "identifier" but it's the thing every other source's
# columns are named after ("the ncbitaxon prefix"), and this lake already
# uses "prefix" for that concept in conversation/docs -- match that, not the
# upstream export's term.
COLUMNS = {
    "identifier": "prefix",
    "name": "name",
    "homepage": "homepage",
    "description": "description",
    "pattern": "lui_pattern",
    "example": "example",
    "uri_format": "uri_format",
    "synonyms": "synonyms",
    "deprecated": "deprecated",
    "part_of": "part_of",
    "provides": "provides",
}

_TYPED = {
    "deprecated": 'TRY_CAST("deprecated" AS BOOLEAN)',
}


def _column_sql(src: str, dst: str) -> str:
    expr = _TYPED.get(src, f'"{src}"')
    return f"{expr} AS {dst}"


def download_registry(settings: Settings | None = None) -> Path:
    """Download the current consensus TSV export into the raw layer.

    Dest is a fixed filename, not date-keyed -- unlike bugsigdb's tagged
    releases, this export has no version identifier of its own to key on; it's
    a rolling snapshot of ``main``, same shape as retractionwatch's CSV.
    """
    s = settings or get_settings()
    dest = raw_dir(_RAW, s) / "registry.tsv"
    dest.unlink(missing_ok=True)  # always re-download; no version to skip-if-present on
    return download(s.bioregistry_registry_url, dest)


def _select_sql(path: Path, limit: int | None) -> str:
    limit_sql = f" LIMIT {int(limit)}" if limit else ""
    select = ",\n            ".join(_column_sql(src, dst) for src, dst in COLUMNS.items())
    # Dialect stated, not sniffed -- same reasoning as every other CSV/TSV
    # source here: free-text columns (description, homepage) can carry commas
    # and quotes. null_padding + strict_mode=false: real rows in this export
    # have fewer trailing tabs than the header when trailing fields are empty
    # (verified: DuckDB's sniffer can't find one dialect that fits every row
    # otherwise) -- ragged real-world data, not a reason to fail the load.
    return f"""
        SELECT {select}
        FROM read_csv({csv_source([path])}, header=true, all_varchar=true,
                      delim='\\t', quote='', escape='',
                      null_padding=true, strict_mode=false)
        {limit_sql}
    """


def curate(
    con: duckdb.DuckDBPyConnection, path: Path, *,
    target: str | None = None, limit: int | None = None,
) -> int:
    """MERGE-upsert the registry export into ``bioregistry`` on ``prefix``."""
    target = target or f"{LAKE}.ref.bioregistry"
    return upsert(con, target, _select_sql(path, limit), key="prefix")


def ingest(
    *, file: str | None = None, schema: str = "ref", limit: int | None = None,
    settings: Settings | None = None,
) -> dict:
    """End-to-end: download (unless ``file``) -> MERGE-upsert -> summary."""
    s = settings or get_settings()
    path = Path(file) if file else download_registry(s)
    target = f"{LAKE}.{schema}.bioregistry"
    con = lake_connect(s)
    try:
        with ops.run(con, source="bioregistry", target=target) as r:
            r.rows = curate(con, path, target=target, limit=limit)
    finally:
        con.close()
    return r.summary()
